# Generated by Django 5.0.1 on 2024-02-05 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_network", "0002_alter_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="post_like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
