# Generated by Django 5.0.1 on 2024-02-05 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_network", "0003_alter_post_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=75)),
                ("slug", models.SlugField(default=uuid.uuid1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="social_network.tag"),
        ),
    ]
