# Generated by Django 5.0.1 on 2024-02-05 17:46

import social_network.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_network", "0004_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["email"]},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", social_network.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="post_like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
