# Generated by Django 5.0.2 on 2024-02-14 18:38

import django.db.models.deletion
import social_network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0005_delete_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=social_network.models.post_image_file_path
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_network.post",
                    ),
                ),
            ],
        ),
    ]
