# Generated by Django 5.0.1 on 2024-02-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_network", "0005_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="social_network.tag"
            ),
        ),
    ]
