# Generated by Django 4.2.10 on 2024-02-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0006_postimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="social_network.post",
            ),
        ),
    ]
