# Generated by Django 5.0.1 on 2024-02-12 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_network", "0006_alter_post_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="user",
            new_name="owner",
        ),
    ]
