# Generated by Django 4.2.10 on 2024-02-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0007_alter_postimage_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(null=True),
        ),
    ]
