# Generated by Django 4.2.10 on 2024-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0009_alter_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="publish_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
