# Generated by Django 4.2.10 on 2024-03-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0010_post_publish_time_alter_post_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
